services:
  ros2-gui:
    image: ros-humble-tors:v0.1
    container_name: ros2_gui_tors
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./ws:/workspace
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    restart: no